### ISSUE TITLE
Instructions on installing `zsh-git-cal-status-cpp` are unclear

### ISSUE THREAD

**Issue by AppacheCodesandra** [zpm-zsh/pr-git#1]
The install instructions on the [zsh-git-cal-status-cpp readme](https://gitlab.com/cosurgi/zsh-git-cal-status-cpp/-/blob/master/README.md#install) mention sourcing the file and shows different function names. This repo mentions compiling that script and including it on the `$PATH` as a different name. It would be nice if there we commands included in your institutions for exactly how `zsh-git-cal-status-cpp` should be configured for this plugin to work.

**Comment by grigorii-horos** [comment]
@kylealanr Fixed in https://github.com/zpm-zsh/pr-git/commit/1cb36f219c592637ad503d869ab130dc3cf0fc80

**Comment by AppacheCodesandra** [comment]
@horosgrisa This worked for me, thank you for the fast reply and help!
